import { deflateSync } from "node:zlib";
import path from "node:path";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { config } from "./config";
import type { ExcalidrawScene } from "./types";

/**
 * Minimal, dependency-free PNG encoder. Enough to produce a real, valid PNG
 * thumbnail that can be stored in /data/thumbnails and served by the app.
 * (A full scene rasterizer would require a headless browser; here we render a
 * deterministic representation seeded from the scene so the file is valid and
 * stable for the thumbnail caching requirement.)
 */

const PNG_SIG = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

let crcTable: number[] | null = null;
function makeCrcTable(): number[] {
  const t = new Array<number>(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    t[n] = c >>> 0;
  }
  return t;
}
function crc32(buf: Buffer): number {
  if (!crcTable) crcTable = makeCrcTable();
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) {
    c = crcTable[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  }
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type: string, data: Buffer): Buffer {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, "ascii");
  const crcInput = Buffer.concat([typeBuf, data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(crcInput), 0);
  return Buffer.concat([len, typeBuf, data, crc]);
}

/** Create a deterministic palette index from the scene. */
function paletteFromScene(scene: ExcalidrawScene): number {
  const n = scene.elements ? scene.elements.length : 0;
  const files = scene.files ? Object.keys(scene.files).length : 0;
  return (n * 3 + files) % 7;
}

/** Render a valid RGBA PNG thumbnail of the given scene (deterministic). */
export function renderScenePng(scene: ExcalidrawScene, width = 320, height = 180): Buffer {
  const palette = [
    [59, 130, 246, 255],
    [16, 185, 129, 255],
    [139, 92, 246, 255],
    [244, 63, 94, 255],
    [245, 158, 11, 255],
    [14, 165, 233, 255],
    [236, 72, 153, 255],
  ];
  const [r, g, b, a] = palette[paletteFromScene(scene)];

  // Raw scanlines (each prefixed with filter byte 0) of RGBA pixels.
  const raw = Buffer.alloc(height * (1 + width * 4));
  for (let y = 0; y < height; y++) {
    const offset = y * (1 + width * 4);
    raw[offset] = 0; // filter: none
    const stripe = Math.floor(y / (height / 12)) % 2 === 0;
    for (let x = 0; x < width; x++) {
      const p = offset + 1 + x * 4;
      const mix = stripe && (x / width > 0.5) ? 0.75 : 1;
      raw[p] = Math.min(255, Math.round(r * mix));
      raw[p + 1] = Math.min(255, Math.round(g * mix));
      raw[p + 2] = Math.min(255, Math.round(b * mix));
      raw[p + 3] = a;
    }
  }
  const idat = deflateSync(raw);

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // color type RGBA
  ihdr[10] = 0; // compression
  ihdr[11] = 0; // filter
  ihdr[12] = 0; // interlace

  return Buffer.concat([
    PNG_SIG,
    chunk("IHDR", ihdr),
    chunk("IDAT", idat),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

function clamp(n: number): number {
  return Math.max(0, Math.min(255, n));
}

export interface ThumbnailResult {
  /** Relative path from DATA_DIR, e.g. "thumbnails/<docId>.png" */
  relativePath: string;
  absolutePath: string;
}

/** Persist a thumbnail for a given key under /data/thumbnails. */
export function saveThumbnail(key: string, scene: ExcalidrawScene): ThumbnailResult {
  const cfg = config();
  const safeKey = key.replace(/[^a-zA-Z0-9._-]/g, "_");
  const name = `${safeKey}.png`;
  const absolutePath = path.join(cfg.thumbnailsDir, name);
  mkdirSync(path.dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, renderScenePng(scene));
  return { relativePath: `thumbnails/${name}`, absolutePath };
}

/** Persist a real PNG buffer generated by the client under /data/thumbnails. */
export function saveThumbnailFromBuffer(key: string, pngBuffer: Buffer): ThumbnailResult {
  const cfg = config();
  const safeKey = key.replace(/[^a-zA-Z0-9._-]/g, "_");
  const name = `${safeKey}.png`;
  const absolutePath = path.join(cfg.thumbnailsDir, name);
  mkdirSync(path.dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, pngBuffer);
  return { relativePath: `thumbnails/${name}`, absolutePath };
}

export function removeThumbnail(relativePath: string | null): void {
  if (!relativePath) return;
  const cfg = config();
  const abs = path.join(cfg.dataDir, relativePath);
  if (abs.startsWith(cfg.dataDir + path.sep)) {
    rmSync(abs, { force: true });
  }
}